proyecto/encuestas/urls.py
from django.urls import path

from . import views

app_name = "encuestas"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detalle"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="resultados"),
    path("<int:question_id>/voto/", views.voto, name="voto"),
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("encuestas/", include("encuestas.urls")),
    path("admin/", admin.site.urls),
]

proyecto/encuestas/models.py
import datetime

from django.db import models
from django.utils import timezone

class Encuesta(models.Model):
    texto_encuesta = models.CharField(max_length=200)
    fecha_publ = models.DateTimeField("fecha de publicacion")
    def __str__(self):
        return self.texto_encuesta
    def fue_publicado_recientemente(self):
        return self.fecha_publ >= timezone.now() - datetime.timedelta(days=1)

class Respuesta(models.Model):
    encuesta = models.ForeignKey(Encuesta, on_delete=models.CASCADE)
    texto_respuesta = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    def __str__(self):
        return self.texto_respuesta

proyecto/encuestas/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from .models import Encuesta, Respuesta
from django.urls import reverse
from django.views import generic

class IndexView(generic.ListView):
    template_name = "encuestas/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Encuesta.objects.order_by("-fecha_publ")[:5]


class DetailView(generic.DetailView):
    model = Encuesta
    template_name = "encuestas/detalle.html"


class ResultsView(generic.DetailView):
    model = Encuesta
    template_name = "encuestas/resultados.html"

def voto(request, question_id):
    question = get_object_or_404(Encuesta, pk=question_id)
    try:
        selected_choice = question.respuesta_set.get(pk=request.POST["respuesta"])
    except (KeyError, Respuesta.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "encuestas/detalle.html",
            {
                "encuesta": question,
                "error_message": "No seleccionaste una opción.",
            },
        )
    else:
        selected_choice.votos = F("votos") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("encuestas:resultados", args=(question.id,)))

proyecto/encuestas/templates/encuestas/detalle.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalle</title>
</head>
<body>
    <form action="{% url 'encuestas:voto' encuesta.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ encuesta.texto_encuesta }}</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for respuesta in encuesta.respuesta_set.all %}
                <input type="radio" name="respuesta" id="respuesta{{ forloop.counter }}" value="{{ respuesta.id }}">
                <label for="respuesta{{ forloop.counter }}">{{ respuesta.texto_respuesta }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="voto">
    </form>
</body>
</html>

proyecto/encuestas/templates/encuestas/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    {% if latest_question_list %}
    <ul>
    {% for encuesta in latest_question_list %}
        <li><a href="{% url 'encuestas:detalle' encuesta.id %}">{{ encuesta.texto_encuesta }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No hay encuestas disponibles.</p>    
    {% endif %}
</body>
</html>

proyecto/encuestas/templates/encuestas/resultados.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resultados</title>
</head>
<body>
    <h1>{{ encuesta.texto_encuesta }}</h1>

    <ul>
    {% for respuesta in encuesta.respuesta_set.all %}
        <li>{{ respuesta.texto_respuesta }} -- {{ respuesta.votos }} voto{{ respuesta.votos|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'encuestas:detalle' encuesta.id %}">Votar de nuevo?</a>
</body>
</html>